# Generated by Django 5.0.5 on 2024-05-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_id",
        ),
        migrations.AddField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="0",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
