# Generated by Django 4.2.13 on 2024-05-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerceapp", "0004_orders_orderupdate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orders",
            old_name="sip_code",
            new_name="zip_code",
        ),
    ]
